# Generated by Django 3.0 on 2021-08-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Currency', models.CharField(max_length=3)),
                ('Price', models.IntegerField()),
                ('Category', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=100)),
                ('Available', models.BooleanField()),
            ],
        ),
    ]
